# Generated by Django 5.2.8 on 2025-11-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_listings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
