# Generated by Django 5.2.8 on 2025-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favourite_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_listings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
