# Generated by Django 5.2.8 on 2025-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
