# Generated by Django 5.2.8 on 2025-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_token',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
