# Generated by Django 5.2.8 on 2025-12-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_messages.conversation'),
        ),
    ]
