# Generated by Django 5.2.8 on 2025-12-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_messages', '0002_message_conv_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='real_estate_conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='real_estate_messages',
        ),
    ]
