# Generated by Django 5.2.8 on 2025-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_messages', '0003_alter_conversation_table_alter_message_table'),
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='users.user'),
        ),
    ]
