# Generated by Django 5.2.8 on 2025-11-17 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_onsale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('AMD', 'Armenian Dram')], default='USD', max_length=3)),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land'), ('villa', 'Villa'), ('office', 'Office Space')], max_length=20)),
                ('country', models.CharField(default='Armenia', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('square_meters', models.PositiveIntegerField()),
                ('land_area', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('new_construction', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('heating_type', models.CharField(blank=True, choices=[('gas', 'Gas Heating'), ('electric', 'Electric Heating'), ('central', 'Central Heating'), ('none', 'No Heating')], max_length=50)),
                ('main_image', models.CharField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
