# Generated by Django 5.2.8 on 2025-11-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.user'),
            preserve_default=False,
        ),
    ]
