# Generated by Django 5.2.8 on 2025-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_image',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
