# Generated by Django 5.2.8 on 2025-11-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_images_alter_listing_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='main_image',
        ),
    ]
