# Generated by Django 5.2.8 on 2025-11-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_main_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='real_estate_listings',
        ),
    ]
